/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package natebanking;

/**
 *
 * @author SK
 */
public class welcomfram extends javax.swing.JFrame {

    /**
     * Creates new form welcomfram
     */
    public welcomfram() {
    
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        background = new javax.swing.JPanel();
        label = new javax.swing.JLabel();
        jlabellogo = new javax.swing.JLabel();
        subhading = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/banklogo-xl.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        background.setBackground(new java.awt.Color(0, 51, 255));
        background.setLayout(null);

        label.setBackground(new java.awt.Color(255, 255, 255));
        label.setFont(new java.awt.Font("Constantia", 0, 36)); // NOI18N
        label.setForeground(java.awt.Color.white);
        label.setText(" Welcome to S K  Banking");
        background.add(label);
        label.setBounds(250, 240, 470, 64);

        jlabellogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imag/banklogo-xl.png"))); // NOI18N
        background.add(jlabellogo);
        jlabellogo.setBounds(340, 20, 230, 210);

        subhading.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        subhading.setForeground(new java.awt.Color(255, 255, 255));
        subhading.setText("India's Number One Online Bank");
        background.add(subhading);
        subhading.setBounds(330, 290, 410, 20);
        background.add(jProgressBar1);
        jProgressBar1.setBounds(20, 410, 890, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(background, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(background, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(welcomfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(welcomfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(welcomfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(welcomfram.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        welcomfram wel=new welcomfram();
          wel.setVisible(true);      
             logingpag log=new  logingpag();   
          try{
              for(int i=0; i<100;i++){
                  Thread.sleep(60);
                  wel.jProgressBar1.setValue(i);
              }
          }catch(Exception e){
              
          }
          wel.setVisible(false);
          log.setVisible(true);
          wel.dispose();
                  
    
    }
       
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel background;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel jlabellogo;
    private javax.swing.JLabel label;
    private javax.swing.JLabel subhading;
    // End of variables declaration//GEN-END:variables
}
